---
# This playbook connects to the public_api network
# 

- name: Request port and attach interface to instance
  # load OpenStack credentials
  # load variables e.g. network, tenant, instance ID
  # neutron port-create...
  # nova interface-attach

- name: Add extra ethernet interface inside instance
  template: src=ifcfg-eth.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{{ item.device }}} owner=root group=root mode=644
  with_items: networks
  notify:
   - restart network
