---
# This playbook contains common plays that will be run on all nodes.

- name: Enable EPEL
  yum: name=epel-release state=present

- name: Install Ansible and Git and common utilities
  yum: state=present name={{ item }}
  with_items: 
     - ansible
     - git
     - vim-enhanced
     - screen
     - tmux
     - tcpdump
     - nc
     - emacs

- name: Update all packages
  yum: name=* state=latest
